### ISSUE TITLE
An error occurred (InvalidParametersException) when calling the ProvisionProduct operation: A stack named sandbox1 already exists

### ISSUE THREAD

**Issue by ghost** [hashicorp/learn-terraform-aws-control-tower-aft#3]
Hi,

When pushing changes for `learn-terraform-aft-account-request` I had the following:

```
  control_tower_parameters = {
    AccountEmail              = "aws-sandbox1@gmail.com"
    AccountName               = "sandbox1"
    ManagedOrganizationalUnit = "Learn AFT"
    SSOUserEmail              = "(my email)"
    SSOUserFirstName          = "(my first name)"
    SSOUserLastName           = "(my last name)"
  }
```
  
 Notice that I forgot to change the OU and that OU didn't exist in my Org. I don't believe I received an error (I not longer have the CloudWatch Logs). However, no account was created. I then changed the OU and code to the following:
 
 ```
  control_tower_parameters = {
    AccountEmail              = "aws-sandbox1@gmail.com"
    AccountName               = "sandbox1"
    ManagedOrganizationalUnit = "Sandbox"
    SSOUserEmail              = "(my email)"
    SSOUserFirstName          = "(my first name)"
    SSOUserLastName           = "(my last name)"
  }
```

I now get an error that says the following:

```
[ERROR] InvalidParametersException: An error occurred (InvalidParametersException) when calling the ProvisionProduct operation: A stack named sandbox1 already exists.
Traceback (most recent call last):
  File "/var/task/aft_account_request_processor.py", line 50, in lambda_handler
    response = create_new_account(
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py", line 283, in create_new_account
    response = client.provision_product(
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

I can find no such stacks in CloudFormation or ServiceCatalog. How can I find and delete this stack?

**Comment by ghost** [comment]
Solved it. Had to go into Provisioned Products and change filter from User to Account.
